spring.application.name=TradeAgent
alpaca.base-url=https://data.alpaca.markets/v2
alpaca.api-key=REMOVED_ALPACA_API_KEY
alpaca.api-secret=REMOVED_ALPACA_SECRET_KEY
alpaca.default-symbol=AAPL
alpaca.default-timeframe=1Day
alpaca.default-limit=60
